feat: add dev dependencies and linter, prettier, editorconfig rules
ReactJS-BA/sitio-web pull request #1
Opened 2021-05-29 01:38 UTC by rodrigo398

## PR Area

- [x] Frontend

## Type of change

_What kind of change does this PR introduce?_

- [x] Feature

## Description

**The main idea of this PR is basically to define some conventions for linter rules**
- Add new dev dependencies for lint rules
- Add lint, prettier, editorconfig rules and ignore files
- Remove import of React lib as it is not needed for version 17

#### Evidence screenshots

## Reviewer checklist

- [x] I have run the code (If applicable)
- [ ] I have reviewed and run any integration tests (if applicable)

_All the points in **[Security & risks](#risks)** above are:_

- [x] Not present or have been mitigated 👍

2021-05-29 01:42 UTC, rodrigo398 commented
Agregue algunas dev dependencies para definir algunas rules de linter, prettier y editorconfig, segun esta card: https://github.com/ReactJS-BA/sitio-web/projects/1#card-62074056 . 

Cualquier sugerencia es mas que bienvenida.

2021-06-24 22:58 UTC, nanovazquez requested changes

2021-06-24 22:58 UTC, nanovazquez commented on .editorconfig
> +indent_size = 4
Cambias a `2`? Preferimos usar ese valor por defecto.

2021-06-24 22:58 UTC, nanovazquez commented on .eslintrc.js
> +}
Vamos con la configuración por defecto recomendada por [@typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#configuration). Podes hacer el cambio?

```
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint',
  ],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
  ],
};```

2021-06-24 22:58 UTC, nanovazquez commented on .prettierrc
> +}
Vamos también por lo que prettier da por defecto. Podes quitar este archivo?

2021-06-24 22:58 UTC, nanovazquez commented on .eslintrc.js
> +}
Además, podes sumar la configuración de prettier? https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#usage-with-prettier

2021-06-24 22:58 UTC, nanovazquez commented on docs/pull_request_template.md
> +- [ ] Not present or have been mitigated 👍
Muy bueno! Pero podemos pasar (esto mismo) a castellano?

2021-06-24 22:58 UTC, nanovazquez commented on package.json
> +    "lint": "eslint src/ --ext .ts,.tsx"
Muy bueno!

2021-06-25 18:55 UTC, rodrigo398 commented on .editorconfig
> +indent_size = 4
Gracias por la review Mariano. Ya hice el cambio a 2 👍

2021-06-25 18:57 UTC, rodrigo398 commented on .eslintrc.js
> +}
Me parece genial ir la configuracion por defecto recomendada por Typescript. Vamos por esa.

2021-06-25 18:57 UTC, rodrigo398 commented on .prettierrc
> +}
Done!

2021-06-25 18:58 UTC, rodrigo398 commented on docs/pull_request_template.md
> +- [ ] Not present or have been mitigated 👍
Me parecio bueno agregar este template, como para que sirva de guia para todos. Ya lo pase a castellano.

2021-06-27 19:00 UTC, nanovazquez approved these changes

2021-06-27 19:00 UTC, nanovazquez commented
LGTM! 👍

2021-06-27 19:01 UTC, merged