maquetado de la seccion de SOCIAL , intale react Icons
ReactJS-BA/sitio-web pull request #2
Opened 2021-05-30 21:12 UTC by Miguel-Andres

Hola , me faltaria linkear los iconos con las redes sociales correspondientes , Me interesa Tener el Diseño y los Assets para guiarme mas facil , Es mi primer PR en un proyecto remoto

2021-06-04 10:06 UTC, rodrigo398 commented
Gracias por el aporte Luis. Felicitaciones por el primer PR 🎉 .  Excelente iniciativa de agregar esos icons para social networks, son bastantes utiles para el sitio de ReactJS. Como ya lo mencionaste, seria genial tener los assets y designs para tener una guia y continuar laburando sobre eso. Esperemos a ver que opinan los demas sobre estos cambios antes de mergear.

2021-06-24 23:09 UTC, leilaybnz requested changes

2021-06-24 23:09 UTC, leilaybnz commented on src/Social/Social.css
> +
Hola! Podrías eliminar los saltos de línea que están de más? Gracias!

2021-06-24 23:09 UTC, leilaybnz commented on src/Social/Social.tsx
> +    </React.Fragment>
Pensás poner otro contenedor a la misma altura que el div social? Sino, no es necesario usar Fragment.

2021-06-24 23:09 UTC, leilaybnz commented on src/Social/Social.tsx
> +          <li> <div className="socialIcons" > <TiSocialTwitter size={40} /></div>Twitter</li>
Podrías enviarnos un screenshot de esta sección? Principalmente para ver si es necesario utilizar un div para contener los iconos, o si podemos hacerlo más semántico. Así podemos darte una opinión más certera!

2021-06-24 23:16 UTC, nanovazquez commented
Hola @Miguel-Andres ! Podes encontrar el diseño aquí: https://www.figma.com/file/74vsJs9FtgDHbvJSWyS8Ui/React-BA?node-id=205%3A1

No tenemos que seguirlo 100% al pie de la letra, pero si respetar las definiciones de diseño.

2021-06-25 18:17 UTC, leilaybnz requested changes

2021-06-25 18:17 UTC, leilaybnz commented on src/Social/Social.tsx
> +          <li> <div className="socialIcons" ><SiSlack size={40}/></div> Slack</li>
Teniendo en cuenta que los **divs** no son elementos con peso semántico, podrías agregarle el atributo _role_ y el _aria-label_? Esto permite que las personas que utilizan lectores de pantalla puedan entender que tenemos íconos para cada red social. Acá te dejo un ejemplo y la [docu](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img) 
< div **role**="img" **aria-label**="Descripcion del icono" >

2021-06-30 07:05 UTC, rodrigo398 commented
@Miguel-Andres podrias por favor mergear los ultimos cambios de `main` a tu `branch`?, de esta manera podes tener este `PR` en sync con `main`, y ademas se corregirian algunos detalles con respecto a saltos de linea e indentacion tambien. Avisame si necesitas una mano con eso y lo hacemos juntos.

2021-07-01 03:19 UTC, Miguel-Andres commented on src/Social/Social.tsx
> +          <li> <div className="socialIcons" > <TiSocialTwitter size={40} /></div>Twitter</li>
![social](https://user-images.githubusercontent.com/55957677/124059743-faa6f400-da01-11eb-86bc-66e0eff2d37e.png)

2021-07-01 05:39 UTC, Miguel-Andres commented
@rodrigo398 @leilaybnz  Hola Gracias por las aclaraciones , intente hacer lo que me comentaron , estoy atento a cualquier otra corrección ,  si hay algo que no estoy teniendo en cuenta con respeto al manejo de github  es mi primera vez colaborando en un proyecto en remoto . Asi que no estoy muy pulido con esta forma de colaborar PERO nada que GOOGLE  no pueda Solucionar  y tambien  me sirve de mucho su feedback .........Gracias !

2021-07-01 09:54 UTC, rodrigo398 commented
@Miguel-Andres gracias por los cambios. Faltarian algunos detalles minimos y esperar el feedback sobre los demas cambios que te solicitaron. No se bien si hay urls para los icons, quizas @leilaybnz podria ayudar con eso.

2021-07-12 22:23 UTC, leilaybnz commented
> @Miguel-Andres gracias por los cambios. Faltarian algunos detalles minimos y esperar el feedback sobre los demas cambios que te solicitaron. No se bien si hay urls para los icons, quizas @leilaybnz podria ayudar con eso.

Acá les mando las urls para los iconos:
**Twitter:** https://twitter.com/React_BA
**Slack:** slack://channel?team=T0434657X&id=C045DPHNR
**Meetup:** https://www.meetup.com/React-en-Buenos-Aires/
**YouTube:** https://www.youtube.com/channel/UC8lMWXElwhflZxWqsE6BuPQ
**Email:** reactjs.ba@gmail.com

2021-08-04 09:52 UTC, merged

2021-08-04 09:56 UTC, rodrigo398 commented
PR revisado y mergeado. Los cambios faltantes se van a agregar en siguientes PRs.